/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bf7aad8c-6b77-4809-abab-7f244b76f562",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ofRgVTtwN",
    "aws_user_pools_web_client_id": "7j6pn6pfvt3f2ild1pu2gc69al",
    "oauth": {
        "domain": "contributortoolkit9f8b3538-9f8b3538-local.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "contributortoolkit://",
        "redirectSignOut": "contributortoolkit://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
